version: '3.8'

services:
 web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
 db:
    image: postgres:16.1
    volumes:
      - postgres:${POSTGRES_DATA_PATH}
    # worth noting that we should be using docker secrets
    env_file:
      - .env

volumes:
    postgres: