# Generated by Django 5.0 on 2023-12-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIIBRAiK', '0003_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='student'),
        ),
    ]
